// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

'use client';

import { initializeFirebase } from '.';
import { FirebaseProvider } from './provider';

// Initialize Firebase on the client
const { app, auth, firestore, storage } = initializeFirebase();

/**
 * A client-side component that initializes Firebase and provides it to its children.
 *
 * This component should be used at the root of your application to ensure that
 * Firebase is initialized and available to all components.
 *
 * @param {object} props - The properties for the component.
 * @param {React.ReactNode} props.children - The child components to render.
 * @returns {React.ReactElement} The rendered component.
 */
export function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FirebaseProvider app={app} auth={auth} firestore={firestore} storage={storage}>
      {children}
    </FirebaseProvider>
  );
}
